// Pip-Boy Maps — Transport Data
// Schedules for Antwerp, Brussels, Moscow, Balashikha

import type { TransportLine } from './store';

export interface CityTransport {
  id: string;
  name: string;
  nameRu: string;
  lines: TransportLine[];
}

export const cityTransports: CityTransport[] = [
  {
    id: 'antwerp',
    name: 'Antwerp',
    nameRu: 'Антверпен',
    lines: [
      {
        id: 'an_bus_1',
        type: 'bus',
        number: '1',
        name: 'Hoboken - Groenplaats',
        from: 'Hoboken P+R',
        to: 'Groenplaats',
        schedule: '05:30 - 23:00 | every 10 min',
        city: 'antwerp',
        notes: 'Weekday frequency',
      },
      {
        id: 'an_bus_17',
        type: 'bus',
        number: '17',
        name: 'Schoonselhof - Centraal',
        from: 'Schoonselhof',
        to: 'Antwerpen Centraal',
        schedule: '06:00 - 22:00 | every 15 min',
        city: 'antwerp',
      },
      {
        id: 'an_bus_22',
        type: 'bus',
        number: '22',
        name: 'Merksem - Linkeroever',
        from: 'Merksem',
        to: 'Linkeroever',
        schedule: '05:45 - 23:15 | every 12 min',
        city: 'antwerp',
      },
      {
        id: 'an_tram_2',
        type: 'tram',
        number: '2',
        name: 'Hoboken - Merksem',
        from: 'Hoboken',
        to: 'Merksem',
        schedule: '05:00 - 00:30 | every 8 min',
        city: 'antwerp',
        notes: 'Main line, runs frequently',
      },
      {
        id: 'an_tram_4',
        type: 'tram',
        number: '4',
        name: 'Hoboken - Groenplaats',
        from: 'Hoboken',
        to: 'Groenplaats',
        schedule: '05:30 - 00:00 | every 10 min',
        city: 'antwerp',
      },
      {
        id: 'an_tram_6',
        type: 'tram',
        number: '6',
        name: 'Olympiade - Luchtbal',
        from: 'Olympiade',
        to: 'Luchtbal',
        schedule: '05:15 - 23:45 | every 12 min',
        city: 'antwerp',
      },
      {
        id: 'an_tram_12',
        type: 'tram',
        number: '12',
        name: 'Sportpaleis - Centraal',
        from: 'Sportpaleis',
        to: 'Antwerpen Centraal',
        schedule: '06:00 - 22:00 | every 15 min',
        city: 'antwerp',
        notes: 'Event line — Sportpaleis',
      },
    ],
  },
  {
    id: 'brussels',
    name: 'Brussels',
    nameRu: 'Брюссель',
    lines: [
      {
        id: 'br_metro_1',
        type: 'metro',
        number: '1',
        name: 'Stockel - Weststation',
        from: 'Stockel',
        to: 'Weststation',
        schedule: '05:30 - 00:30 | every 6 min',
        city: 'brussels',
        notes: 'East-West line',
      },
      {
        id: 'br_metro_5',
        type: 'metro',
        number: '5',
        name: 'Hermann-Debroux - Erasme',
        from: 'Hermann-Debroux',
        to: 'Erasme',
        schedule: '05:30 - 00:30 | every 7 min',
        city: 'brussels',
        notes: 'Main east-west line',
      },
      {
        id: 'br_metro_6',
        type: 'metro',
        number: '6',
        name: 'Roi Baudouin - Simonis',
        from: 'Roi Baudouin',
        to: 'Simonis (EL)',
        schedule: '05:30 - 00:30 | every 8 min',
        city: 'brussels',
      },
      {
        id: 'br_bus_71',
        type: 'bus',
        number: '71',
        name: 'Molens - Montgomery',
        from: 'Molens',
        to: 'Montgomery',
        schedule: '06:00 - 21:00 | every 15 min',
        city: 'brussels',
      },
      {
        id: 'br_tram_81',
        type: 'tram',
        number: '81',
        name: 'Heysel - Montgomery',
        from: 'Heysel',
        to: 'Montgomery',
        schedule: '05:30 - 23:00 | every 10 min',
        city: 'brussels',
      },
      {
        id: 'br_tram_92',
        type: 'tram',
        number: '92',
        name: 'Schaerbeek - Fort-Jaco',
        from: 'Schaerbeek Gare',
        to: 'Fort-Jaco',
        schedule: '05:15 - 23:30 | every 8 min',
        city: 'brussels',
        notes: 'Major north-south line',
      },
      {
        id: 'br_train',
        type: 'train',
        number: 'S1',
        name: 'Antwerp - Brussels - Nivelles',
        from: 'Anvers-Central',
        to: 'Nivelles',
        schedule: '05:00 - 23:30 | every 15 min',
        city: 'brussels',
        notes: 'S-train Brabant',
      },
    ],
  },
  {
    id: 'moscow',
    name: 'Moscow',
    nameRu: 'Москва',
    lines: [
      {
        id: 'ms_metro_1',
        type: 'metro',
        number: '1',
        name: 'Bulvar Rokossovskogo - Business Center',
        from: 'Бульвар Рокоссовского',
        to: 'Бизнес-центр',
        schedule: '05:30 - 01:00 | every 2-3 min',
        city: 'moscow',
        notes: 'Сокольническая линия (красная)',
      },
      {
        id: 'ms_metro_2',
        type: 'metro',
        number: '2',
        name: 'Khimki - Koterlnikovskaya',
        from: 'Химки',
        to: 'Котельники',
        schedule: '05:25 - 01:05 | every 2-3 min',
        city: 'moscow',
        notes: 'Замоскворецкая линия (зелёная)',
      },
      {
        id: 'ms_metro_5',
        type: 'metro',
        number: '5',
        name: 'Koltsevaya (Circle)',
        from: 'Парк Культуры',
        to: 'Парк Культуры',
        schedule: '05:25 - 01:00 | every 2 min',
        city: 'moscow',
        notes: 'Кольцевая линия (коричневая)',
      },
      {
        id: 'ms_mcc_14',
        type: 'train',
        number: 'МЦК',
        name: 'Moscow Central Circle',
        from: 'Лужники',
        to: 'Лужники',
        schedule: '05:45 - 00:30 | every 4-5 min',
        city: 'moscow',
        notes: 'Московское центральное кольцо',
      },
      {
        id: 'ms_bus_м1',
        type: 'bus',
        number: 'М1',
        name: 'Sokolniki - Ploshchad Ilicha',
        from: 'Сокольники',
        to: 'Площадь Ильича',
        schedule: '06:00 - 00:00 | every 5 min',
        city: 'moscow',
      },
      {
        id: 'ms_bus_м9',
        type: 'bus',
        number: 'М9',
        name: 'Kotelniki - Metro Krasnoselskaya',
        from: 'Котельники',
        to: 'м. Красносельская',
        schedule: '05:45 - 23:30 | every 8 min',
        city: 'moscow',
      },
    ],
  },
  {
    id: 'balashikha',
    name: 'Balashikha',
    nameRu: 'Балашиха',
    lines: [
      {
        id: 'bl_bus_1',
        type: 'bus',
        number: '1',
        name: 'Mikrorayon Gagarina - Zhulebino',
        from: 'мкр. Гагарина',
        to: 'Жулебино',
        schedule: '06:00 - 22:30 | every 10 min',
        city: 'balashikha',
      },
      {
        id: 'bl_bus_14',
        type: 'bus',
        number: '14',
        name: 'Fabrika 1 Maya - Metro Novogireevo',
        from: 'Фабрика 1 Мая',
        to: 'м. Новогиреево',
        schedule: '05:30 - 23:00 | every 8 min',
        city: 'balashikha',
        notes: 'Direct to metro Moscow',
      },
      {
        id: 'bl_bus_17',
        type: 'bus',
        number: '17',
        name: 'Balashikha - Reutov',
        from: 'Балашиха (автостанция)',
        to: 'Реутов',
        schedule: '06:00 - 22:00 | every 12 min',
        city: 'balashikha',
      },
      {
        id: 'bl_bus_21',
        type: 'bus',
        number: '21',
        name: 'Sovetsky - Metro Pervomaiskaya',
        from: 'Советский',
        to: 'м. Первомайская',
        schedule: '05:45 - 23:15 | every 10 min',
        city: 'balashikha',
        notes: 'Direct to metro Moscow',
      },
      {
        id: 'bl_bus_28',
        type: 'bus',
        number: '28',
        name: 'Saltykovskaya - Metro Shchelkovskaya',
        from: 'Салтыковская',
        to: 'м. Щёлковская',
        schedule: '05:30 - 22:45 | every 12 min',
        city: 'balashikha',
      },
      {
        id: 'bl_train',
        type: 'train',
        number: 'Электричка',
        name: 'Balashikha - Moscow (Kurskaya)',
        from: 'Балашиха',
        to: 'Москва (Курская)',
        schedule: '05:00 - 00:30 | every 15-20 min',
        city: 'balashikha',
        notes: 'Горьковское направление МЦД-4',
      },
    ],
  },
];

export function getTransportTypeLabel(type: string, lang: 'ru' | 'en'): string {
  const labels: Record<string, Record<string, string>> = {
    bus: { ru: 'Автобус', en: 'Bus' },
    tram: { ru: 'Трамвай', en: 'Tram' },
    metro: { ru: 'Метро', en: 'Metro' },
    train: { ru: 'Поезд', en: 'Train' },
  };
  return labels[type]?.[lang] || type;
}

export function getTransportIcon(type: string): string {
  const icons: Record<string, string> = {
    bus: '🚌',
    tram: '🚋',
    metro: '🚇',
    train: '🚂',
  };
  return icons[type] || '📍';
}
